version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t akashdeep-final .
      - docker tag akashdeep-final:latest 522814723398.dkr.ecr.us-east-1.amazonaws.com/akashdeep-flask-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 522814723398.dkr.ecr.us-east-1.amazonaws.com/akashdeep-flask-app:latest
